import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Earth & Parchment Design Tokens
        "surface-container-highest": "#e6e2de",
        "on-error-container": "#93000a",
        "inverse-primary": "#cec894",
        "on-tertiary-container": "#5e6767",
        "secondary-fixed-dim": "#c8c7ba",
        "on-secondary-container": "#636359",
        "surface-dim": "#ddd9d6",
        "primary-fixed": "#eae4ae",
        "surface-container": "#f1ede9",
        "on-secondary-fixed-variant": "#47473e",
        "secondary": "#5f5f55",
        "on-secondary-fixed": "#1b1c14",
        "inverse-on-surface": "#f4f0ec",
        "secondary-container": "#e1e0d3",
        "inverse-surface": "#31302e",
        "outline-variant": "#cac7b8",
        "primary": "#636034",
        "error-container": "#ffdad6",
        "surface-tint": "#636034",
        "on-secondary": "#ffffff",
        "background": "#fdf9f5",
        "on-primary-fixed-variant": "#4b481f",
        "secondary-fixed": "#e4e3d6",
        "on-primary-fixed": "#1e1c00",
        "on-error": "#ffffff",
        "surface-container-low": "#f7f3ef",
        "on-tertiary-fixed": "#151d1d",
        "surface-variant": "#e6e2de",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dbe4e4",
        "on-background": "#1c1c19",
        "outline": "#7a776a",
        "surface-bright": "#fdf9f5",
        "surface": "#fdf9f5",
        "on-surface-variant": "#49473c",
        "on-surface": "#1c1c19",
        "tertiary": "#576060",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ece6af",
        "tertiary-fixed-dim": "#bfc8c8",
        "tertiary-container": "#dde6e6",
        "primary-fixed-dim": "#cec894",
        "surface-container-high": "#ebe7e4",
        "on-tertiary-fixed-variant": "#404849",
        "error": "#ba1a1a",
        "on-primary-container": "#6b673b",
        "on-primary": "#ffffff",

        // Status semantic colors
        success: {
          DEFAULT: "#2e7d32",
          light: "#e8f5e9",
          dark: "#1b5e20",
        },
        warning: {
          DEFAULT: "#ed6c02",
          light: "#fff4e5",
          dark: "#e65100",
        },
        info: {
          DEFAULT: "#0288d1",
          light: "#e1f5fe",
          dark: "#01579b",
        },
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        body: ["var(--font-anybody)", "Anybody", "sans-serif"],
        label: ["var(--font-work-sans)", "Work Sans", "sans-serif"],
        mono: ["monospace"],
      },
      boxShadow: {
        parchment: "0 4px 20px -2px rgba(121, 119, 116, 0.08)",
        "parchment-lg": "0 10px 30px -4px rgba(121, 119, 116, 0.12)",
        "parchment-elevated": "0 20px 40px -8px rgba(99, 96, 52, 0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
